export const canvas = document.getElementById("gameCanvas");
export const ctx = canvas.getContext("2d");

export const hud = {
  lives: document.getElementById("lives"),
  gold: document.getElementById("gold"),
  wave: document.getElementById("wave"),
  kills: document.getElementById("kills"),
  msg: document.getElementById("message"),
  mapSelect: document.getElementById("mapSelect"),
  stageSelect: document.getElementById("stageSelect"),
  mapLabel: document.getElementById("mapLabel"),
  stageLabel: document.getElementById("stageLabel"),
  applyStageBtn: document.getElementById("applyStageBtn"),
  waveBtn: document.getElementById("waveBtn"),
  pauseBtn: document.getElementById("pauseBtn"),
  speedBtn: document.getElementById("speedBtn"),
  openMenuBtn: document.getElementById("openMenuBtn"),
  openShortcutHelpBtn: document.getElementById("openShortcutHelpBtn"),
  openSaveBtn: document.getElementById("openSaveBtn"),
  muteBtn: document.getElementById("muteBtn"),
  bgmVolume: document.getElementById("bgmVolume"),
  sfxVolume: document.getElementById("sfxVolume"),
  bgmVolumeValue: document.getElementById("bgmVolumeValue"),
  sfxVolumeValue: document.getElementById("sfxVolumeValue"),
  towerTypeBasicBtn: document.getElementById("towerTypeBasicBtn"),
  towerTypeSlowBtn: document.getElementById("towerTypeSlowBtn"),
  towerTypeSplashBtn: document.getElementById("towerTypeSplashBtn"),
  towerTypeSniperBtn: document.getElementById("towerTypeSniperBtn"),
  towerTypeSupportBtn: document.getElementById("towerTypeSupportBtn"),
  towerInfoPanel: document.getElementById("towerInfoPanel"),
  towerInfoTitle: document.getElementById("towerInfoTitle"),
  towerInfoMeta: document.getElementById("towerInfoMeta"),
  towerInfoStats: document.getElementById("towerInfoStats"),
  towerInfoActions: document.getElementById("towerInfoActions"),
  towerInfoUpgradeBtn: document.getElementById("towerInfoUpgradeBtn"),
  towerInfoBranchABtn: document.getElementById("towerInfoBranchABtn"),
  towerInfoBranchBBtn: document.getElementById("towerInfoBranchBBtn"),
  clearConditionLabel: document.getElementById("clearConditionLabel")
  ,waveAutoStatus: document.getElementById("waveAutoStatus")
  ,waveAutoModeLabel: document.getElementById("waveAutoModeLabel")
  ,waveAutoCountdownLabel: document.getElementById("waveAutoCountdownLabel")
  ,waveAutoProgressBar: document.getElementById("waveAutoProgressBar")
};

export const menu = {
  overlay: document.getElementById("mainMenuOverlay"),
  navHomeBtn: document.getElementById("menuNavHomeBtn"),
  navStagesBtn: document.getElementById("menuNavStagesBtn"),
  navCodexBtn: document.getElementById("menuNavCodexBtn"),
  navSettingsBtn: document.getElementById("menuNavSettingsBtn"),
  panelHome: document.getElementById("menuPanelHome"),
  panelStages: document.getElementById("menuPanelStages"),
  panelCodex: document.getElementById("menuPanelCodex"),
  panelSettings: document.getElementById("menuPanelSettings"),
  mapSelect: document.getElementById("menuMapSelect"),
  stageSelect: document.getElementById("menuStageSelect"),
  mapTabs: document.getElementById("menuMapTabs"),
  stageCards: document.getElementById("menuStageCards"),
  stageSelectionText: document.getElementById("menuStageSelectionText"),
  currentMapLabel: document.getElementById("menuCurrentMapLabel"),
  currentStageLabel: document.getElementById("menuCurrentStageLabel"),
  fishCompletionLabel: document.getElementById("menuFishCompletionLabel"),
  towerCompletionLabel: document.getElementById("menuTowerCompletionLabel"),
  saveSlot: document.getElementById("menuSaveSlot"),
  saveSlotMirror: document.getElementById("menuSaveSlotMirror"),
  applySlotBtn: document.getElementById("menuApplySlotBtn"),
  resetSlotBtn: document.getElementById("menuResetSlotBtn"),
  fishCodexList: document.getElementById("menuFishCodexList"),
  fishCodexSummary: document.getElementById("menuFishCodexSummary"),
  towerCodexList: document.getElementById("menuTowerCodexList"),
  towerCodexSummary: document.getElementById("menuTowerCodexSummary"),
  codexDetailOverlay: document.getElementById("menuCodexDetailOverlay"),
  detailType: document.getElementById("menuDetailType"),
  detailTitle: document.getElementById("menuDetailTitle"),
  detailMeta: document.getElementById("menuDetailMeta"),
  detailPreview: document.getElementById("menuDetailPreview"),
  detailBody: document.getElementById("menuDetailBody"),
  detailCloseBtn: document.getElementById("menuDetailCloseBtn"),
  muteBtn: document.getElementById("menuMuteBtn"),
  muteState: document.getElementById("menuMuteState"),
  bgmVolume: document.getElementById("menuBgmVolume"),
  bgmVolumeValue: document.getElementById("menuBgmVolumeValue"),
  sfxVolume: document.getElementById("menuSfxVolume"),
  sfxVolumeValue: document.getElementById("menuSfxVolumeValue"),
  showDamageText: document.getElementById("menuShowDamageText"),
  fxDensity: document.getElementById("menuFxDensity"),
  spriteQuality: document.getElementById("menuSpriteQuality"),
  spriteAutoThreshold: document.getElementById("menuSpriteAutoThreshold"),
  spriteAutoThresholdValue: document.getElementById("menuSpriteAutoThresholdValue"),
  spriteAutoThresholdHint: document.getElementById("menuSpriteAutoThresholdHint"),
  showTowerPanel: document.getElementById("menuShowTowerPanel"),
  showPerfStats: document.getElementById("menuShowPerfStats"),
  autoStartWaves: document.getElementById("menuAutoStartWaves"),
  resetSettingsBtn: document.getElementById("menuResetSettingsBtn"),
  codexSearch: document.getElementById("menuCodexSearch"),
  codexTypeFilter: document.getElementById("menuCodexTypeFilter"),
  codexSizeFilter: document.getElementById("menuCodexSizeFilter"),
  codexSkillFilter: document.getElementById("menuCodexSkillFilter"),
  goStagesBtn: document.getElementById("menuGoStagesBtn"),
  stageStartBtn: document.getElementById("menuStageStartBtn"),
  backHomeBtn: document.getElementById("menuBackHomeBtn"),
  codexToStagesBtn: document.getElementById("menuCodexToStagesBtn"),
  codexCloseBtn: document.getElementById("menuCodexCloseBtn"),
  settingsToStagesBtn: document.getElementById("menuSettingsToStagesBtn"),
  settingsCloseBtn: document.getElementById("menuSettingsCloseBtn"),
  startBtn: document.getElementById("menuStartBtn"),
  closeBtn: document.getElementById("menuCloseBtn")
};

export const resultUi = {
  overlay: document.getElementById("resultOverlay"),
  kicker: document.getElementById("resultKicker"),
  title: document.getElementById("resultTitle"),
  summary: document.getElementById("resultSummary"),
  starsRule: document.getElementById("resultStarsRule"),
  unlockHint: document.getElementById("resultUnlockHint"),
  stats: document.getElementById("resultStats"),
  retryBtn: document.getElementById("resultRetryBtn"),
  nextBtn: document.getElementById("resultNextBtn"),
  menuBtn: document.getElementById("resultMenuBtn")
};

export const overlays = {
  bossAlert: document.getElementById("bossAlert"),
  bossAlertBadge: document.getElementById("bossAlertBadge"),
  bossAlertText: document.getElementById("bossAlertText"),
  bossAlertTimer: document.getElementById("bossAlertTimer")
};
